### ISSUE TITLE
Gem Still Getting Maintained?

### ISSUE THREAD

**Issue by Jngai** [jmettraux/rufus-decision#16]
Hi is this library still getting maintained and are the associated dependencies still getting maintained as well? Also is this library rails 4.2 compatible ?

**Comment by jmettraux** [comment]
Hello,

the library isn't really maintained anymore. The associated "rufus-" dependencies are not maintained anymore.

I never used the library with Rails. It's only a Ruby library, Rails or not, it doesn't matter.

I will flag the library as "dead" or simply "unmaintained".
